### ISSUE TITLE
cannot find module 'svelte-persisted-store'

### ISSUE THREAD

**Issue by alejdig** [steveninety/svelte-email-tailwind#12]
import Preview from "svelte-email-tailwind/preview/preview.svelte";

<script lang="ts">
  import Preview from "svelte-email-tailwind/preview/preview.svelte";
  export let data;
</script>

<Preview {data} email="name@example.com" />

cannot find module 'svelte-persisted-store' imported from '.../node_modules/.pnpm/svelte-email-tailwind@1.0.2/node_modules/svelte-email-tailwind/preview/preview.svelte'

**Comment by clibequilibrium** [comment]
> import Preview from "svelte-email-tailwind/preview/preview.svelte";
> 
> <script lang="ts"> import Preview from "svelte-email-tailwind/preview/preview.svelte"; export let data; </script>
> <Preview {data} email="[name@example.com](mailto:name@example.com)" />
> 
> cannot find module 'svelte-persisted-store' imported from '.../node_modules/.pnpm/svelte-email-tailwind@1.0.2/node_modules/svelte-email-tailwind/preview/preview.svelte'

`npm i svelte-persisted-store`

**Comment by steveninety** [comment]
Latest version (v2.0.1) uses it as a regular dependency instead of dev dependency, so that fixes the issue.
