### ISSUE TITLE
svelte  <4.2.19 warning

### ISSUE THREAD

**Issue by trentb-daycos** [steveninety/svelte-email-tailwind#13]
Really like this package but we are getting the warning when installing:
```
svelte  <4.2.19
Severity: moderate
Svelte has a potential mXSS vulnerability due to improper HTML escaping - https://github.com/advisories/GHSA-8266-84wp-wv5c
No fix available
node_modules/svelte-email-tailwind/node_modules/svelte
  svelte-email-tailwind  *
  Depends on vulnerable versions of svelte
  node_modules/svelte-email-tailwind
```
Hoping it wouldn't be too difficult to update to use at least svelte  4.2.19, not sure if it would cause problems or not but others here don't wish to use with the above warning.
Thanks!

**Comment by steveninety** [comment]
Since Svelte 5 has been released, I've been trying to find some time to update this package to make it v5 compatible! Will get to it ASAP...

**Comment by steveninety** [comment]
v1.0.3 now uses the latest Svelte 4 version.
v2.0.1 uses Svelte 5.

**Comment by trentb-daycos** [comment]
Thanks!!!
