### ISSUE TITLE
"Cannot find module 'resend' imported from node.modules/svelte-email-tailwind/preview.index.js."

### ISSUE THREAD

**Issue by cmjoseph07** [steveninety/svelte-email-tailwind#5]
"Cannot find module 'resend' imported from node.modules/svelte-email-tailwind/preview.index.js."

Getting this error when attempting to exactly replicate the nodemailer config route portion. Do you need resend or do you have any advise how to resolve?

**Comment by steveninety** [comment]
If you update to the latest version, then using nodemailer should work. Let me know if anything's wrong!
